# -*- coding: utf-8 -*-
"""Practical1_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7DObEqyXOCiMapAOtIwsPhSfin4sYwF
"""

!pip install nltk
!pip install textblob

import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag
from textblob import TextBlob

text = """This December I went on a vacation to Mahabaleshwar which is a Hill Station with my Family.The Weather was cool and refreshing , which made the trip more enjoyable. We had a great time with our family with delicious food every day."""

tokens = word_tokenize(text)

ps = PorterStemmer()
stems = [ps.stem(word) for word in tokens]

lemmatizer = WordNetLemmatizer()
lemmas = [lemmatizer.lemmatize(word) for word in tokens]

pos_tags = pos_tag(tokens)

blob = TextBlob(text)
sentiment = blob.sentiment

print("Tokens:", tokens)
print("Stems:", stems)
print("Lemmas:", lemmas)
print("POS Tags:", pos_tags)
print("Sentiment:", sentiment)
